### ISSUE TITLE
如何实现页脚紧贴页面底部

### ISSUE THREAD

**Issue by chenxiaochun** [chenxiaochun/blog#31]
## 第一种方法

```html
<div class="wrapper">这是wapper</div>
<footer>这里是footer</footer>
```
```css
body{
    margin: 0;
    display: flex;
    flex-flow: column;
    min-height: 100vh;
}
.wrapper{
    background: #ccc;
    flex: 1;
    text-align: center;
}
footer{
    height: 80px;
    background: #333;
    color: #fff;
    text-align: center;
}
```
